export type TrafficLight = "green" | "yellow" | "red";

export type DeckSlide =
  | {
      id: string;
      layout: "title";
      kicker: string;
      title: string;
      subtitle: string;
      meta: string;
    }
  | {
      id: string;
      layout: "agenda";
      kicker: string;
      title: string;
      items: { n: string; label: string }[];
    }
  | {
      id: string;
      layout: "cards";
      kicker: string;
      title: string;
      lede?: string;
      cards: { title: string; copy: string }[];
    }
  | {
      id: string;
      layout: "quote";
      kicker: string;
      title: string;
      examples: { bad: string; why: string }[];
      note: string;
    }
  | {
      id: string;
      layout: "split";
      kicker: string;
      title: string;
      leftTitle: string;
      left: string[];
      rightTitle: string;
      right: string[];
    }
  | {
      id: string;
      layout: "flow";
      kicker: string;
      title: string;
      steps: { n: string; title: string; copy: string }[];
    }
  | {
      id: string;
      layout: "lights";
      kicker: string;
      title: string;
      lede: string;
      bands: { light: TrafficLight; range: string; meaning: string }[];
      footnote: string;
    }
  | {
      id: string;
      layout: "scorecard";
      kicker: string;
      title: string;
      rows: {
        project: string;
        account: string;
        percent: number;
        light: TrafficLight;
        gap: string;
      }[];
    }
  | {
      id: string;
      layout: "table";
      kicker: string;
      title: string;
      headers: [string, string];
      rows: [string, string][];
    }
  | {
      id: string;
      layout: "ask";
      kicker: string;
      title: string;
      items: string[];
      close: string;
    }
  | {
      id: string;
      layout: "diagram";
      kicker: string;
      title: string;
      lede: string;
      lanes: {
        n: string;
        label: string;
        nodes: { title: string; copy: string }[];
      }[];
    };

export const DECK: { title: string; slides: DeckSlide[] } = {
  title: "InfraCop MCP",
  slides: [
    {
      id: "title",
      layout: "title",
      kicker: "Tech leadership briefing",
      title: "Stop inventing bicycles in Terraform.",
      subtitle:
        "InfraCop MCP is the mandatory enterprise-standards server for every agent that writes infrastructure — one policy, every AWS account, every team.",
      meta: "5+ DevOps teams · 20+ AWS accounts · 2 Organizations",
    },
    {
      id: "agenda",
      layout: "agenda",
      kicker: "Agenda",
      title: "What we need to decide.",
      items: [
        { n: "01", label: "The cost of each team inventing its own Terraform" },
        { n: "02", label: "Why Confluence and Copilot skill files failed" },
        { n: "03", label: "The operating model — from a PR to a paged SRE" },
        { n: "04", label: "A traffic-light compliance skill for leadership" },
      ],
    },
    {
      id: "bicycles",
      layout: "cards",
      kicker: "Problem",
      title: "Five teams. Twenty bicycles.",
      lede:
        "Each DevOps squad writes Terraform the way the last senior left it. Production certification waits on that drift. Auditors find it. Finance cannot roll it up. On-call cannot name an owner.",
      cards: [
        {
          title: "Certification delay",
          copy: "Every new service re-argues tags, names, regions, and OPA gates in review. Release trains slip while reviewers reconstruct the unwritten standard.",
        },
        {
          title: "Audit findings",
          copy: "Public databases, missing owner tags, and off-allow-list regions keep showing up because the rule lived in a person's head, not in the agent's loop.",
        },
        {
          title: "FinOps is fiction",
          copy: "CostCentre, Project, and Team are optional in practice. Showback and rightsizing reports cannot be trusted across 20+ accounts.",
        },
        {
          title: "No owner at 02:00",
          copy: "Alerts fire on db-prod, MyDatabase, or a 17-character hash. Nobody knows who to page — or whether the resource is even production.",
        },
      ],
    },
    {
      id: "names",
      layout: "quote",
      kicker: "Ownership blackout",
      title: "Names that cannot be paged.",
      examples: [
        { bad: "db-prod", why: "Which product? Which team? Which account?" },
        { bad: "MyDatabase", why: "Laptop naming leaked into production." },
        { bad: "tf-aws-rds-8f3c21", why: "Autogenerated. Useless in PagerDuty." },
        { bad: "test-bucket-final-v2", why: "Is this safe to delete on Friday?" },
      ],
      note: "Enterprise pattern is kebab {app}-{env}-{type}-{id}, 47 characters, env token required — so an alert already carries the owner and the blast radius.",
    },
    {
      id: "cleanup",
      layout: "cards",
      kicker: "Hygiene",
      title: "Cleanup is guesswork without Env.",
      lede:
        "When production and playground share an account — or when two Organizations drift — you cannot retire spend you cannot classify.",
      cards: [
        {
          title: "No Env / Environment tags",
          copy: "Weekend auto-stop and holiday-pause cannot be applied safely. Production gets paused, or UAT lives forever at production prices.",
        },
        {
          title: "No directory contract",
          copy: "catalog-info.yaml and /envs/production are supposed to win. Today a .tfvars leftover from a fork still ships Env=dev into prod.",
        },
        {
          title: "Two AWS Organizations",
          copy: "The same bicycle is reinvented per org. A cleanup script that works in org A deletes the wrong RDS in org B.",
        },
      ],
    },
    {
      id: "finops",
      layout: "cards",
      kicker: "Money",
      title: "FinOps cannot start from random tags.",
      cards: [
        {
          title: "Allocation",
          copy: "Without mandatory CostCentre and Project:{org}:{component}, CUR reports become a spreadsheet archaeology project every quarter.",
        },
        {
          title: "Rightsizing",
          copy: "You cannot ask a team to cut a 2xl if Owner and Team are blank. The ticket bounces until someone greps Git history.",
        },
        {
          title: "Unit cost",
          copy: "Service-level cost needs Service + Env. Cryptic names make that join impossible. Leadership sees a blob, not a product.",
        },
      ],
    },
    {
      id: "before",
      layout: "split",
      kicker: "Before",
      title: "Standards lived where people left them.",
      leftTitle: "Then — Confluence",
      left: [
        "Individual pages, different spaces, no owner after a leaver.",
        "New DevOps joiners were pointed at a wiki tree and never opened it again.",
        "Reviewers cited tribal knowledge, not a versioned rule id.",
        "Production certification became a negotiation, not a gate.",
      ],
      rightTitle: "Recently — Copilot / Claude skill files",
      right: [
        "Moved into .md skills inside Claude and GitHub Copilot.",
        "Still copies. Twenty-plus AWS accounts, two Organizations, no refresh.",
        "A standard released on Monday is stale in a fork by Thursday.",
        "Agents also listen to HashiCorp Terraform MCP and AWS skills — and those win on conflict.",
      ],
    },
    {
      id: "after",
      layout: "flow",
      kicker: "After",
      title: "One MCP. Mandatory in every Terraform repo.",
      steps: [
        {
          n: "1",
          title: "Versioned source",
          copy: "Ent-DevOps-Standards GitHub repo. Individual .md files. A release is the contract.",
        },
        {
          n: "2",
          title: "Ingest on release",
          copy: "Webhook chunks, embeds with Titan V2, upserts Qdrant. Rule ids replace the previous version.",
        },
        {
          n: "3",
          title: "Agents retrieve first",
          copy: "enterprise_get_standards before any .tf is written. Validate before the PR is considered done.",
        },
        {
          n: "4",
          title: "Precedence 100",
          copy: "InfraCop beats Terraform MCP (40) and AWS skills (30) on every conflict. Policy, not a suggestion.",
        },
      ],
    },
    {
      id: "map",
      layout: "diagram",
      kicker: "Operating model",
      title: "From a standards PR to a paged SRE.",
      lede:
        "One versioned release feeds the MCP, every Terraform agent, Cost Explorer, and Datadog. Tags and names are the same contract.",
      lanes: [
        {
          n: "01",
          label: "Write the standard",
          nodes: [
            { title: "Authors", copy: "Change a .md rule. Open a PR." },
            { title: "Standards repo", copy: "Ent-DevOps-Standards. One file per rule." },
            { title: "Team leads", copy: "Review, approve, tag a versioned release." },
          ],
        },
        {
          n: "02",
          label: "Ingest and serve",
          nodes: [
            { title: "Release webhook", copy: "Reads new .md. Chunks. Embeds Titan V2." },
            { title: "Qdrant", copy: "Vector index. A release replaces the prior version." },
            { title: "MCP + console", copy: "RAG at precedence 100. Operator console." },
          ],
        },
        {
          n: "03",
          label: "Write the infrastructure",
          nodes: [
            { title: "5 DevOps teams", copy: "Agents write Terraform for each project’s AWS." },
            { title: "Infra repos", copy: "Mandatory mcp.json. Retrieve before emitting HCL." },
            { title: "Named, tagged AWS", copy: "{app}-{env}-{type}-{id} plus Owner, Project, Env." },
          ],
        },
        {
          n: "04",
          label: "Operate with the same contract",
          nodes: [
            { title: "FinOps · Cost Explorer", copy: "ProjectX staging $XXX vs production $XX, 3 accounts." },
            { title: "Datadog", copy: "Tags and names route a prod alert to the owning SRE." },
            { title: "SRE team", copy: "Pages production. Ignores non-prod. Knows the owner." },
          ],
        },
      ],
    },
    {
      id: "traffic",
      layout: "lights",
      kicker: "Leadership skill",
      title: "Traffic-light on every infrastructure codebase.",
      lede:
        "A separate InfraCop skill — enterprise_compliance_score — scores a project's Terraform against the live standard. Tech leadership sees a light, not a 40-page audit.",
      bands: [
        {
          light: "green",
          range: "100%",
          meaning: "All mandatory rules pass. Safe to certify and release.",
        },
        {
          light: "yellow",
          range: "65–85%",
          meaning: "Improvement plan required this quarter. Do not expand the footprint.",
        },
        {
          light: "red",
          range: "< 65%",
          meaning: "Escalate. Block production certification until the gap closes.",
        },
      ],
      footnote:
        "Green is reserved for all-compliant. Scores 86–99% stay Yellow until remaining mandatory failures are closed. Recommended-only findings do not move the light.",
    },
    {
      id: "scorecard",
      layout: "scorecard",
      kicker: "Example portfolio",
      title: "What leadership would see on Monday.",
      rows: [
        {
          project: "payments-api",
          account: "prod-payments",
          percent: 100,
          light: "green",
          gap: "None — tags, names, regions, no public RDS",
        },
        {
          project: "checkout-bff",
          account: "prod-retail",
          percent: 78,
          light: "yellow",
          gap: "Missing CostCentre on 4 modules; two names without env token",
        },
        {
          project: "data-scratch",
          account: "shared-analytics",
          percent: 41,
          light: "red",
          gap: "Public RDS, us-west-2, Owner blank, cleanup candidates unnamed",
        },
      ],
    },
    {
      id: "compare",
      layout: "table",
      kicker: "Before / after",
      title: "What changes when the config is mandatory.",
      headers: ["Before", "After InfraCop MCP"],
      rows: [
        [
          "Standards scattered on Confluence; abandoned on attrition",
          "One GitHub repo. A release is the only way a rule changes",
        ],
        [
          "New joiners do not use the standard in daily work",
          "The agent must retrieve it before it emits Terraform",
        ],
        [
          "Claude / Copilot .md skills go stale across 20+ accounts",
          "Webhook re-ingests on every standards release",
        ],
        [
          "HashiCorp and AWS MCP examples win on conflict",
          "InfraCop precedence 100. Other MCPs are references only",
        ],
        [
          "Certification is a human negotiation",
          "enterprise_validate_terraform is fail-closed. Light is public",
        ],
        [
          "Leadership hears about drift in the audit",
          "Traffic-light per repo, every Monday, before the auditor",
        ],
      ],
    },
    {
      id: "ask",
      layout: "ask",
      kicker: "Decision",
      title: "Make InfraCop MCP mandatory.",
      items: [
        "Add infracop-mcp to every Terraform repository as required agent config (mcp.json + AGENTS.md).",
        "Point the Ent-DevOps-Standards GitHub release webhook at ingest. No other copy of the standard is authoritative.",
        "Turn on enterprise_compliance_score as a PR check and a weekly leadership scorecard.",
        "Treat Yellow as a tracked improvement item. Treat Red as a release block.",
      ],
      close: "One bicycle. Maintained. Ridden by every agent that writes our infrastructure.",
    },
  ],
};
