/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as StandardsSlugRouteImport } from './routes/standards.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsSlugRoute = StandardsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StandardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/brief': typeof BriefRoute
  '/inspector': typeof InspectorRoute
  '/pipeline': typeof PipelineRoute
  '/playground': typeof PlaygroundRoute
  '/research': typeof ResearchRoute
  '/standards': typeof StandardsRouteWithChildren
  '/standards/$slug': typeof StandardsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/brief': typeof BriefRoute
  '/inspector': typeof InspectorRoute
  '/pipeline': typeof PipelineRoute
  '/playground': typeof PlaygroundRoute
  '/research': typeof ResearchRoute
  '/standards': typeof StandardsRouteWithChildren
  '/standards/$slug': typeof StandardsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/brief': typeof BriefRoute
  '/inspector': typeof InspectorRoute
  '/pipeline': typeof PipelineRoute
  '/playground': typeof PlaygroundRoute
  '/research': typeof ResearchRoute
  '/standards': typeof StandardsRouteWithChildren
  '/standards/$slug': typeof StandardsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/architecture'
    | '/brief'
    | '/inspector'
    | '/pipeline'
    | '/playground'
    | '/research'
    | '/standards'
    | '/standards/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/architecture'
    | '/brief'
    | '/inspector'
    | '/pipeline'
    | '/playground'
    | '/research'
    | '/standards'
    | '/standards/$slug'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/architecture'
    | '/brief'
    | '/inspector'
    | '/pipeline'
    | '/playground'
    | '/research'
    | '/standards'
    | '/standards/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BriefRoute: typeof BriefRoute
  InspectorRoute: typeof InspectorRoute
  PipelineRoute: typeof PipelineRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ResearchRoute: typeof ResearchRoute
  StandardsRoute: typeof StandardsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/$slug': {
      id: '/standards/$slug'
      path: '/$slug'
      fullPath: '/standards/$slug'
      preLoaderRoute: typeof StandardsSlugRouteImport
      parentRoute: typeof StandardsRoute
    }
  }
}

interface StandardsRouteChildren {
  StandardsSlugRoute: typeof StandardsSlugRoute
}

const StandardsRouteChildren: StandardsRouteChildren = {
  StandardsSlugRoute: StandardsSlugRoute,
}

const StandardsRouteWithChildren = StandardsRoute._addFileChildren(
  StandardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ArchitectureRoute: ArchitectureRoute,
  BriefRoute: BriefRoute,
  InspectorRoute: InspectorRoute,
  PipelineRoute: PipelineRoute,
  PlaygroundRoute: PlaygroundRoute,
  ResearchRoute: ResearchRoute,
  StandardsRoute: StandardsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
